resolver: lts-13.26

extra-deps:
  - relude-0.5.0

  # logging
  - co-log-0.3.0.0
  - ansi-terminal-0.9       # for co-log
  - chronos-1.0.5           # for co-log
  - co-log-core-0.2.0.0     # for co-log
  - torsor-0.1              # for co-log
  - typerep-map-0.3.2       # for co-log

  # github
  - github-0.22
  - binary-instances-1
  - binary-orphans-1.0.1
  - time-compat-1.9.2.2

  # testing
  - hedgehog-1.0

  - postgresql-simple-named-0.0.0.0
  - servant-0.16.0.1
  - servant-server-0.16
  - tomland-1.0.0
  - unliftio-0.2.12
  - unliftio-core-0.1.2.0
