resolver: lts-13.23

extra-deps:
  - ansi-terminal-0.9
  - co-log-0.3.0.0
  - co-log-core-0.2.0.0
  - chronos-1.0.5
  - github-0.20
  - torsor-0.1 # for chronos
  - relude-0.5.0
  - servant-0.16.0.1
  - servant-server-0.16
  - tomland-1.0.0
  - typerep-map-0.3.2
